# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hurl < Formula
  desc "A powerful tool for sending HTTP requests"
  homepage "https://github.com/neil-and-void/hurl"
  version "0.2.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/neil-and-void/hurl/releases/download/v0.2.2/hurl_0.2.2_darwin_arm64.tar.gz"
      sha256 "c40c496a18ff92506ea292451ddc61fcae75658ef7e19043f845741cc54ed360"

      def install
        bin.install "hurl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/neil-and-void/hurl/releases/download/v0.2.2/hurl_0.2.2_darwin_amd64.tar.gz"
      sha256 "ff833b5b659d29da4f8719f3322e94230c5941ebc341bbdcc6693d882d977b92"

      def install
        bin.install "hurl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/neil-and-void/hurl/releases/download/v0.2.2/hurl_0.2.2_linux_arm64.tar.gz"
      sha256 "0d573cfdbbf02ad4acfd5bed10b7bd1b44c4a78368cc2904c351a9415d253aa5"

      def install
        bin.install "hurl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/neil-and-void/hurl/releases/download/v0.2.2/hurl_0.2.2_linux_amd64.tar.gz"
      sha256 "45f1ff7a13abe41870aaefb9bb07913230ffbb9139144bd419a88900c0cdfa1c"

      def install
        bin.install "hurl"
      end
    end
  end

  def caveats
    <<~EOS
      Thanks for installing hurl!
    EOS
  end
end
