# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hurl < Formula
  desc "A powerful tool for sending HTTP requests"
  homepage "https://github.com/neil-and-void/homebrew-hurl"
  version "0.2.4"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/neil-and-void/hurl/releases/download/v0.2.4/hurl_0.2.4_darwin_arm64.tar.gz"
      sha256 "57d036964fb6a51b4a3b19bdb05fd6a15605bc0bfd57bff3ba064d782f61599a"

      def install
        bin.install "hurl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/neil-and-void/hurl/releases/download/v0.2.4/hurl_0.2.4_darwin_amd64.tar.gz"
      sha256 "ed0ee69ad4779eac0e8c8c1c13cdb904046292cd4c52d8f9820183df12a780cd"

      def install
        bin.install "hurl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/neil-and-void/hurl/releases/download/v0.2.4/hurl_0.2.4_linux_arm64.tar.gz"
      sha256 "e0fc5e148f3e65ae884815251f00c859fd8995cc0266d9cbe5973d7dc39e4e38"

      def install
        bin.install "hurl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/neil-and-void/hurl/releases/download/v0.2.4/hurl_0.2.4_linux_amd64.tar.gz"
      sha256 "23c0b70a0309f426bfdf5ef52d35ba813a30a5140d5775a394267bb9048084bf"

      def install
        bin.install "hurl"
      end
    end
  end

  def caveats
    <<~EOS
      Thanks for installing hurl!
    EOS
  end
end
