# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hurl < Formula
  desc "Postman for terminal workflows"
  homepage "https://github.com/neil-and-void/hurl"
  version "0.2.7"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/neil-and-void/hurl/releases/download/v0.2.7/hurl_Darwin_arm64.tar.gz"
      sha256 "7527e5b89c4584e6c1073b1fca289bad06f5038e1f65bf5f81c3ddf30ba8e670"

      def install
        bin.install "hurl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/neil-and-void/hurl/releases/download/v0.2.7/hurl_Darwin_x86_64.tar.gz"
      sha256 "06c82dc5379f09c7ce33f0825ef4c1f205e43b6c1dd153f89f1afa9af8d285cb"

      def install
        bin.install "hurl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/neil-and-void/hurl/releases/download/v0.2.7/hurl_Linux_arm64.tar.gz"
      sha256 "1bcecff5608e45a47c43cb122a9610a8255b2a6a0e847f80849e41d21fe8ff31"

      def install
        bin.install "hurl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/neil-and-void/hurl/releases/download/v0.2.7/hurl_Linux_x86_64.tar.gz"
      sha256 "18f6168d5e3336f067f5e0a90d40bb27168fbec9d06a505206af258aa3ed3f10"

      def install
        bin.install "hurl"
      end
    end
  end

  def caveats
    <<~EOS
      Thanks for installing hurl!
    EOS
  end
end
