# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hurl < Formula
  desc "Postman for terminal workflows"
  homepage "https://github.com/neil-and-void/homebrew-hurl"
  version "0.2.5"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/neil-and-void/hurl/releases/download/v0.2.5/hurl_Darwin_arm64.tar.gz"
      sha256 "4dfd3742c7581af55f30e5c684168a3d628b2fe075a64a052d262d32d9cf7275"

      def install
        bin.install "hurl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/neil-and-void/hurl/releases/download/v0.2.5/hurl_Darwin_x86_64.tar.gz"
      sha256 "d6e52e52485f388132e237843ef4ccfb64bb922c21476459501c6735526f9f0a"

      def install
        bin.install "hurl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/neil-and-void/hurl/releases/download/v0.2.5/hurl_Linux_arm64.tar.gz"
      sha256 "991d9d9fe4b7261b05646f63c52cbbff6cf36b22b9f10efd2d0233668f73c61a"

      def install
        bin.install "hurl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/neil-and-void/hurl/releases/download/v0.2.5/hurl_Linux_x86_64.tar.gz"
      sha256 "c95a76516959337722117451df1a8fb8285a82cd778746a0fe36902cebf6c37f"

      def install
        bin.install "hurl"
      end
    end
  end

  def caveats
    <<~EOS
      Thanks for installing hurl!
    EOS
  end
end
